logging:
  level:
    ru.yandex.practicum.filmorate: INFO
    ru.yandex.practicum.filmorate.controller: DEBUG
    ru.yandex.practicum.filmorate.service: DEBUG
    ru.yandex.practicum.filmorate.managment: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %-5level - %logger{36} - %msg%n"
  file:
    name: logs/filmorate.log
    max-size: 10MB
    max-history: 10